### ISSUE TITLE
Not downloading 

### ISSUE THREAD

**Issue by cacoch** [lt20kmph/pmail#2]
Throw this error. 
```
INFO::2021-02-13 15:56:18::[server]: Listening on port 5656.
INFO::2021-02-13 15:56:18::[server]: Userinfo for: joedoe@gmail.com does not exist.
ERROR::2021-02-13 15:56:26::[server]: Unable to update DB, trying again soon.
Traceback (most recent call last):
  File "/data/pmail/pmail/server.py", line 688, in syncDb
    _syncDb_freq(s, newMessagesArrived, lock)
  File "/data/pmail/pmail/server.py", line 622, in _syncDb_freq
    setupAttachments(account)
  File "/data/pmail/pmail/common.py", line 499, in setupAttachments
    for f in currentFilters['filter']:
KeyError: 'filter'
... and repeat again and again
```

**Comment by lt20kmph** [comment]
It could be because you don't have any filters I guess (in which case if the API request returns an empty json it would cause this error). Can you confirm this by visiting: https://developers.google.com/gmail/api/reference/rest/v1/users.settings.filters/list and using the 'Try this API' with your userid and post the response here? Many thanks.

**Comment by cacoch** [comment]
I got this :
200 ok

```
{
  "filter": [
    {
      "id": "xyz",
      "criteria": {
        "from": "newsletters@zdnet.online.com"
      },
      "action": {
        "addLabelIds": [
          "Label_4"
        ],
        "removeLabelIds": [
          "INBOX"
        ]
      }
    },
    {
      "id": "xyz",
      "criteria": {
        "from": "cnet_networks_member_services@newsletter.online.com"
      },
      "action": {
        "addLabelIds": [
          "Label_4"
        ],
        "removeLabelIds": [
          "INBOX"
        ]
      }
    }
  ]
}
```

**Comment by lt20kmph** [comment]
Hmm.. Odd so it is not what I thought it might be, I have put a script `minimalRequest.py` in the `pmail` directory. Can you try running this script like: 

     python minimalRequest.py '/path/to/your/credentials.json' 

and see what happens, it should print out a list of labels and filters after asking you to confirm permissions.
